### PR TITLE
perform radical pkexecectomy

### PR DESCRIPTION
**Pull request by barak**

### CODE REVIEW

**Comment by gregkh** [comment]
Thanks for this, I forgot about removing this stuff.

**Comment by ferdnyc** [comment]
The patient lives! \o/

**Comment by barak** [comment]
Yes, the operation was a success.
https://tracker.debian.org/pkg/usbview

**Comment by ferdnyc** [comment]
3.0 also just hit all currently supported Fedora releases today. Without _these_ changes, but still. Next time. (Hopefully before 2034!) 🤣

**Pull request merged**
